# Homework Weekend 6
## PCA - Principal Component Analysis
### Sources
#### Reading:
- https://georgemdallas.wordpress.com/2013/10/30/principal-component-analysis-4-dummies-eigenvectors-eigenvalues-and-dimension-reduction/<br>
- https://medium.com/@aptrishu/understanding-principle-component-analysis-e32be0253ef0<br>
- https://towardsdatascience.com/a-one-stop-shop-for-principal-component-analysis-5582fb7e0a9c<br>
- https://towardsdatascience.com/the-mathematics-behind-principal-component-analysis-fff2d7f4b643<br>

#### Coding:
- https://medium.com/@raghavan99o/principal-component-analysis-pca-explained-and-implemented-eeab7cb73b72 <br>

### Setting up Workshop

In [44]:
## Import Libraries
# Arrays and Array Math
import numpy as np

## Settings
# Set Random Seed
np.random.seed(1)

### 01 Data Mining

In [45]:
## Generate Data
# Lets begin by generating random data with 3 dimensions with 40 samples.
# We will have two class with 20 samples per class.

In [46]:
# Create Mold for Class 1
vec1 = np.array([0, 0, 0])
mat1 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
# Generate Class 1
sample_for_class1 = np.random.multivariate_normal(vec1, mat1, 20).T
# Force Sample into Shape
assert sample_for_class1.shape == (3, 20), "The dimension of the sample_for_class1 matrix is not 3x20"

In [47]:
# Create Mold for Class 2
vec2 = np.array([1, 1, 1])
mat2 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
# Generate Class 2
sample_for_class2 = np.random.multivariate_normal(vec2, mat2, 20).T
# Force Sample into Shape
assert sample_for_class2.shape == (3, 20), "The dimension of the sample_for_class2 matrix is not 3x20"

In [48]:
# Forge Class 1 and 2 together
all_data = np.concatenate((sample_for_class1, sample_for_class2), axis=1)
# Force Data into Shape
assert all_data.shape == (3, 40), "The dimension of the all_data matrix is not 3x20"

### Next Step

In [49]:
# Calculate Mean of each Dimension
mean_dim1 = np.mean(all_data[0, :])
mean_dim2 = np.mean(all_data[1, :])
mean_dim3 = np.mean(all_data[2, :])
# Calculate Mean-Vector
mean_vector = np.array([[mean_dim1], [mean_dim2], [mean_dim3]])
print('The Mean Vector:\n', mean_vector)

The Mean Vector:
 [[0.41667492]
 [0.69848315]
 [0.49242335]]


In [50]:
all_data.shape[1]

40

In [51]:
## Create Scatter Matrix
'An estimation of covariance matrix when covariance cannot be calculated or costly to calculate'
'Covariance Matrix is a matrix of each variables varianze with the other.'
# Set up Scatter Matrix with 3x3 Zeroes
scatter_matrix = np.zeros((3,3))
# Cycle through all Observations
for i in range(all_data.shape[1]):
    scatter_matrix += (all_data[:, i].reshape(3, 1) - mean_vector).dot((all_data[:, i].reshape(3, 1) - mean_vector).T)
print('The Scatter Matrix is :\n', scatter_matrix)

The Scatter Matrix is :
 [[38.4878051  10.50787213 11.13746016]
 [10.50787213 36.23651274 11.96598642]
 [11.13746016 11.96598642 49.73596619]]


In [52]:
## Calculate Eigenvector and Eigenvalue
# Eignevector
# Eigenvalue
eig_val, eig_vec = np.linalg.eig(scatter_matrix)

In [53]:
for ev in eig_vec:
    np.testing.assert_array_almost_equal(1.0, np.linalg.norm(ev))

<i><b>Correct Code:</b> Turn eig_val_sc into eig_val and eig_val_sc into eig_val</i>

In [54]:
# We Make a list of tuple containing (eigenvalue, eigenvector)
eig_pairs = [(np.abs(eig_val[i]), eig_vec[:,i]) for i in range(len(eig_val))]

# We then Sort list of tuples by the eigenvalue
eig_pairs.sort(key=lambda x: x[0], reverse=True)

# verify that the list is correctly sorted by decreasing eigenvalues
for i in eig_pairs:
    print(i[0])

65.16936779078195
32.69471296321796
26.596203282097097


In [55]:
# Now we choose k the largest eigenvectors 
matrix_w = np.hstack((eig_pairs[0][1].reshape(3,1), eig_pairs[1][1].reshape(3,1)))
print('Matrix W:\n', matrix_w)

Matrix W:
 [[-0.49210223 -0.64670286]
 [-0.47927902 -0.35756937]
 [-0.72672348  0.67373552]]


<i><b>Correct Code:</b> Turn all_samples into all_data</i>

In [57]:
## Transform 
transformed = matrix_w.T.dot(all_data)
assert transformed.shape == (2,40), "The matrix is not 2x40 dimensional."

### Questions
- What exactly is the difference between Class 1 and Class 2?<br>

### Future Works
- Try to recreate the plots.<br>
- Read up on Covariance.<br>
- Read up on Eigenvalue and EigenVector.<br>
- Message Creator about faulty code.<br>